### ISSUE TITLE
Get rid of mutable objects

### ISSUE THREAD

**Issue by Akuli** [Akuli/oomph#68]
- [ ] Add new syntax for `foo = foo.thing()` (perhaps `foo .= thing()` or `foo = .thing()` or `foo (=) .thing()`, see #67)
- [ ] Change `foo.bar = baz` so that it makes a new instance of `foo` (except when not needed, see ideas in #66)
- [ ] Make lists immutable (#66)
